### ISSUE TITLE
gzip 1.6 dependency in net-mist/cmst

### ISSUE THREAD

**Issue by Sqozz** [benkohler/iamben-overlay#2]
Hi there! 
I'm using your cmst-ebuild right now to build cmst on my machine. Right now i encountered the problem, that gzip can't find the --keep parameter and portage aborted the build process. This is because the --keep parameter is introduced in version 1.6 of gzip which is not default in gentoo.
So it whould be nice, if you add >=gzip 1.6 in your ebuild.

**Comment by benkohler** [comment]
Sorry, I never even saw this issue open until just now.  I guess I'm not very good at githubbing.  I'm going to close this issue since it's now 18 months later and there are no affected gzip versions in ::gentoo anymore

Thanks for the report
